# permissions for end users to view stores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: store-viewer-role
rules:
- apiGroups:
  - stores.store.com
  resources:
  - stores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stores.store.com
  resources:
  - stores/status
  verbs:
  - get
